    1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # GUI module generated by PAGE version 5.6
    5 #  in conjunction with Tcl version 8.6
    6 #    Nov 10, 2020 10:34:32 PM EST  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 import option_support
   23 
   24 def vp_start_gui():
   25     '''Starting point when module is the main routine.'''
   26     global val, w, root
   27     root = tk.Tk()
   28     option_support.set_Tk_var()
   29     top = Toplevel1 (root)
   30     option_support.init(root, top)
   31     root.mainloop()
   32 
   33 w = None
   34 def create_Toplevel1(rt, *args, **kwargs):
   35     '''Starting point when module is imported by another module.
   36        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
   37     global w, w_win, root
   38     #rt = root
   39     root = rt
   40     w = tk.Toplevel (root)
   41     option_support.set_Tk_var()
   42     top = Toplevel1 (w)
   43     option_support.init(w, top, *args, **kwargs)
   44     return (w, top)
   45 
   46 def destroy_Toplevel1():
   47     global w
   48     w.destroy()
   49     w = None
   50 
   51 class Toplevel1:
   52     def __init__(self, top=None):
   53         '''This class configures and populates the toplevel window.
   54            top is the toplevel containing window.'''
   55         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
   56         _fgcolor = '#000000'  # X11 color: 'black'
   57         _compcolor = '#d9d9d9' # X11 color: 'gray85'
   58         _ana1color = '#d9d9d9' # X11 color: 'gray85'
   59         _ana2color = '#ececec' # Closest X11 color: 'gray92'
   60 
   61         top.geometry("1019x1031+836+229")
   62         top.minsize(120, 1)
   63         top.maxsize(2564, 1421)
   64         top.resizable(1,  1)
   65         top.title("New Toplevel")
   66         top.configure(background="#d9d9d9")
   67 
   68         self.Labelframe1 = tk.LabelFrame(top)
   69         self.Labelframe1.place(relx=0.079, rely=0.039, relheight=0.081
   70                 , relwidth=0.854)
   71         self.Labelframe1.configure(relief='groove')
   72         self.Labelframe1.configure(foreground="black")
   73         self.Labelframe1.configure(text='''Symbol''')
   74         self.Labelframe1.configure(background="#d9d9d9")
   75 
   76         self.Entry1 = tk.Entry(self.Labelframe1)
   77         self.Entry1.place(relx=0.138, rely=0.476, height=17, relwidth=0.177
   78                 , bordermode='ignore')
   79         self.Entry1.configure(background="white")
   80         self.Entry1.configure(cursor="fleur")
   81         self.Entry1.configure(disabledforeground="#a3a3a3")
   82         self.Entry1.configure(font="TkFixedFont")
   83         self.Entry1.configure(foreground="#000000")
   84         self.Entry1.configure(insertbackground="black")
   85 
   86         self.Label1 = tk.Label(self.Labelframe1)
   87         self.Label1.place(relx=0.011, rely=0.476, height=21, width=104
   88                 , bordermode='ignore')
   89         self.Label1.configure(background="#d9d9d9")
   90         self.Label1.configure(disabledforeground="#a3a3a3")
   91         self.Label1.configure(foreground="#000000")
   92         self.Label1.configure(text='''Input Symbol''')
   93 
   94         self.Data = tk.Button(self.Labelframe1)
   95         self.Data.place(relx=0.379, rely=0.357, height=34, width=127
   96                 , bordermode='ignore')
   97         self.Data.configure(activebackground="#ececec")
   98         self.Data.configure(activeforeground="#000000")
   99         self.Data.configure(background="#d9d9d9")
  100         self.Data.configure(disabledforeground="#a3a3a3")
  101         self.Data.configure(foreground="#000000")
  102         self.Data.configure(highlightbackground="#d9d9d9")
  103         self.Data.configure(highlightcolor="black")
  104         self.Data.configure(pady="0")
  105         self.Data.configure(text='''Load Symbol''')
  106 
  107         self.status = tk.Label(self.Labelframe1)
  108         self.status.place(relx=0.586, rely=0.476, height=21, width=203
  109                 , bordermode='ignore')
  110         self.status.configure(background="#d9d9d9")
  111         self.status.configure(disabledforeground="#a3a3a3")
  112         self.status.configure(foreground="#000000")
  113         self.status.configure(text='''Status: waiting for symbol''')
  114 
  115         self.Labelframe2 = tk.LabelFrame(top)
  116         self.Labelframe2.place(relx=0.079, rely=0.155, relheight=0.196
  117                 , relwidth=0.85)
  118         self.Labelframe2.configure(relief='groove')
  119         self.Labelframe2.configure(foreground="black")
  120         self.Labelframe2.configure(text='''Forecast Setting''')
  121         self.Labelframe2.configure(background="#d9d9d9")
  122 
  123         self.Radiobutton1 = tk.Radiobutton(self.Labelframe2)
  124         self.Radiobutton1.place(relx=0.104, rely=0.149, relheight=0.144
  125                 , relwidth=0.09, bordermode='ignore')
  126         self.Radiobutton1.configure(activebackground="#ececec")
  127         self.Radiobutton1.configure(activeforeground="#000000")
  128         self.Radiobutton1.configure(background="#d9d9d9")
  129         self.Radiobutton1.configure(disabledforeground="#a3a3a3")
  130         self.Radiobutton1.configure(foreground="#000000")
  131         self.Radiobutton1.configure(highlightbackground="#d9d9d9")
  132         self.Radiobutton1.configure(highlightcolor="black")
  133         self.Radiobutton1.configure(justify='left')
  134         self.Radiobutton1.configure(text='''Automatic''')
  135         self.Radiobutton1.configure(variable=option_support.selectedButton)
  136 
  137         self.Radiobutton1_1 = tk.Radiobutton(self.Labelframe2)
  138         self.Radiobutton1_1.place(relx=0.104, rely=0.297, relheight=0.144
  139                 , relwidth=0.09, bordermode='ignore')
  140         self.Radiobutton1_1.configure(activebackground="#ececec")
  141         self.Radiobutton1_1.configure(activeforeground="#000000")
  142         self.Radiobutton1_1.configure(background="#d9d9d9")
  143         self.Radiobutton1_1.configure(cursor="fleur")
  144         self.Radiobutton1_1.configure(disabledforeground="#a3a3a3")
  145         self.Radiobutton1_1.configure(foreground="#000000")
  146         self.Radiobutton1_1.configure(highlightbackground="#d9d9d9")
  147         self.Radiobutton1_1.configure(highlightcolor="black")
  148         self.Radiobutton1_1.configure(justify='left')
  149         self.Radiobutton1_1.configure(text='''Regressive''')
  150         self.Radiobutton1_1.configure(variable=option_support.selectedButton)
  151 
  152         self.Radiobutton1_2 = tk.Radiobutton(self.Labelframe2)
  153         self.Radiobutton1_2.place(relx=0.104, rely=0.446, relheight=0.153
  154                 , relwidth=0.09, bordermode='ignore')
  155         self.Radiobutton1_2.configure(activebackground="#ececec")
  156         self.Radiobutton1_2.configure(activeforeground="#000000")
  157         self.Radiobutton1_2.configure(background="#d9d9d9")
  158         self.Radiobutton1_2.configure(disabledforeground="#a3a3a3")
  159         self.Radiobutton1_2.configure(foreground="#000000")
  160         self.Radiobutton1_2.configure(highlightbackground="#d9d9d9")
  161         self.Radiobutton1_2.configure(highlightcolor="black")
  162         self.Radiobutton1_2.configure(justify='left')
  163         self.Radiobutton1_2.configure(text='''Stationary''')
  164         self.Radiobutton1_2.configure(variable=option_support.selectedButton)
  165 
  166         self.Radiobutton1_3 = tk.Radiobutton(self.Labelframe2)
  167         self.Radiobutton1_3.place(relx=0.081, rely=0.594, relheight=0.134
  168                 , relwidth=0.113, bordermode='ignore')
  169         self.Radiobutton1_3.configure(activebackground="#ececec")
  170         self.Radiobutton1_3.configure(activeforeground="#000000")
  171         self.Radiobutton1_3.configure(background="#d9d9d9")
  172         self.Radiobutton1_3.configure(disabledforeground="#a3a3a3")
  173         self.Radiobutton1_3.configure(foreground="#000000")
  174         self.Radiobutton1_3.configure(highlightbackground="#d9d9d9")
  175         self.Radiobutton1_3.configure(highlightcolor="black")
  176         self.Radiobutton1_3.configure(justify='left')
  177         self.Radiobutton1_3.configure(text='''Bullish''')
  178         self.Radiobutton1_3.configure(variable=option_support.selectedButton)
  179 
  180         self.Radiobutton1_3_1 = tk.Radiobutton(self.Labelframe2)
  181         self.Radiobutton1_3_1.place(relx=0.092, rely=0.743, relheight=0.134
  182                 , relwidth=0.09, bordermode='ignore')
  183         self.Radiobutton1_3_1.configure(activebackground="#ececec")
  184         self.Radiobutton1_3_1.configure(activeforeground="#000000")
  185         self.Radiobutton1_3_1.configure(background="#d9d9d9")
  186         self.Radiobutton1_3_1.configure(disabledforeground="#a3a3a3")
  187         self.Radiobutton1_3_1.configure(foreground="#000000")
  188         self.Radiobutton1_3_1.configure(highlightbackground="#d9d9d9")
  189         self.Radiobutton1_3_1.configure(highlightcolor="black")
  190         self.Radiobutton1_3_1.configure(justify='left')
  191         self.Radiobutton1_3_1.configure(text='''Bearish''')
  192         self.Radiobutton1_3_1.configure(variable=option_support.selectedButton)
  193 
  194         self.Forecast = tk.Button(self.Labelframe2)
  195         self.Forecast.place(relx=0.762, rely=0.198, height=44, width=157
  196                 , bordermode='ignore')
  197         self.Forecast.configure(activebackground="#ececec")
  198         self.Forecast.configure(activeforeground="#000000")
  199         self.Forecast.configure(background="#d9d9d9")
  200         self.Forecast.configure(disabledforeground="#a3a3a3")
  201         self.Forecast.configure(foreground="#000000")
  202         self.Forecast.configure(highlightbackground="#d9d9d9")
  203         self.Forecast.configure(highlightcolor="black")
  204         self.Forecast.configure(pady="0")
  205         self.Forecast.configure(text='''Forecast''')
  206 
  207         self.Forecast_1 = tk.Button(self.Labelframe2)
  208         self.Forecast_1.place(relx=0.762, rely=0.644, height=44, width=157
  209                 , bordermode='ignore')
  210         self.Forecast_1.configure(activebackground="#ececec")
  211         self.Forecast_1.configure(activeforeground="#000000")
  212         self.Forecast_1.configure(background="#d9d9d9")
  213         self.Forecast_1.configure(disabledforeground="#a3a3a3")
  214         self.Forecast_1.configure(foreground="#000000")
  215         self.Forecast_1.configure(highlightbackground="#d9d9d9")
  216         self.Forecast_1.configure(highlightcolor="black")
  217         self.Forecast_1.configure(pady="0")
  218         self.Forecast_1.configure(text='''Chart''')
  219 
  220         self.regressive_input = tk.Entry(self.Labelframe2)
  221         self.regressive_input.place(relx=0.346, rely=0.347, height=17
  222                 , relwidth=0.109, bordermode='ignore')
  223         self.regressive_input.configure(background="white")
  224         self.regressive_input.configure(disabledforeground="#a3a3a3")
  225         self.regressive_input.configure(font="TkFixedFont")
  226         self.regressive_input.configure(foreground="#000000")
  227         self.regressive_input.configure(insertbackground="black")
  228 
  229         self.bulish_input = tk.Entry(self.Labelframe2)
  230         self.bulish_input.place(relx=0.346, rely=0.644, height=17, relwidth=0.109
  231                 , bordermode='ignore')
  232         self.bulish_input.configure(background="white")
  233         self.bulish_input.configure(disabledforeground="#a3a3a3")
  234         self.bulish_input.configure(font="TkFixedFont")
  235         self.bulish_input.configure(foreground="#000000")
  236         self.bulish_input.configure(highlightbackground="#d9d9d9")
  237         self.bulish_input.configure(highlightcolor="black")
  238         self.bulish_input.configure(insertbackground="black")
  239         self.bulish_input.configure(selectbackground="blue")
  240         self.bulish_input.configure(selectforeground="white")
  241 
  242         self.bearish_input = tk.Entry(self.Labelframe2)
  243         self.bearish_input.place(relx=0.346, rely=0.792, height=17
  244                 , relwidth=0.109, bordermode='ignore')
  245         self.bearish_input.configure(background="white")
  246         self.bearish_input.configure(disabledforeground="#a3a3a3")
  247         self.bearish_input.configure(font="TkFixedFont")
  248         self.bearish_input.configure(foreground="#000000")
  249         self.bearish_input.configure(highlightbackground="#d9d9d9")
  250         self.bearish_input.configure(highlightcolor="black")
  251         self.bearish_input.configure(insertbackground="black")
  252         self.bearish_input.configure(selectbackground="blue")
  253         self.bearish_input.configure(selectforeground="white")
  254 
  255         self.Label2 = tk.Label(self.Labelframe2)
  256         self.Label2.place(relx=0.277, rely=0.347, height=21, width=34
  257                 , bordermode='ignore')
  258         self.Label2.configure(background="#d9d9d9")
  259         self.Label2.configure(disabledforeground="#a3a3a3")
  260         self.Label2.configure(foreground="#000000")
  261         self.Label2.configure(text='''Days:''')
  262 
  263         self.Label2_1 = tk.Label(self.Labelframe2)
  264         self.Label2_1.place(relx=0.254, rely=0.644, height=21, width=73
  265                 , bordermode='ignore')
  266         self.Label2_1.configure(activebackground="#f9f9f9")
  267         self.Label2_1.configure(activeforeground="black")
  268         self.Label2_1.configure(background="#d9d9d9")
  269         self.Label2_1.configure(disabledforeground="#a3a3a3")
  270         self.Label2_1.configure(foreground="#000000")
  271         self.Label2_1.configure(highlightbackground="#d9d9d9")
  272         self.Label2_1.configure(highlightcolor="black")
  273         self.Label2_1.configure(text='''Magnitude:''')
  274 
  275         self.Label2_1_1 = tk.Label(self.Labelframe2)
  276         self.Label2_1_1.place(relx=0.254, rely=0.792, height=21, width=73
  277                 , bordermode='ignore')
  278         self.Label2_1_1.configure(activebackground="#f9f9f9")
  279         self.Label2_1_1.configure(activeforeground="black")
  280         self.Label2_1_1.configure(background="#d9d9d9")
  281         self.Label2_1_1.configure(disabledforeground="#a3a3a3")
  282         self.Label2_1_1.configure(foreground="#000000")
  283         self.Label2_1_1.configure(highlightbackground="#d9d9d9")
  284         self.Label2_1_1.configure(highlightcolor="black")
  285         self.Label2_1_1.configure(text='''Magnitude:''')
  286 
  287         self.Labelframe3 = tk.LabelFrame(top)
  288         self.Labelframe3.place(relx=0.079, rely=0.369, relheight=0.598
  289                 , relwidth=0.852)
  290         self.Labelframe3.configure(relief='groove')
  291         self.Labelframe3.configure(foreground="black")
  292         self.Labelframe3.configure(text='''Options''')
  293         self.Labelframe3.configure(background="#d9d9d9")
  294 
  295 if __name__ == '__main__':
  296     vp_start_gui()
  297 
  298 

